#!/bin/bash

[ -z "$1" ] && echo "Usage: $0 filename.html" && exit

filename="$1"

#html document title
TITLE="${filename%.*}"
#path to highlight.js folder
HL_PATH="highlight"
#the syntax highlighting style from highlight.js
HL_STYLE="pojoaque.css"
#path to your css files location
USR_STYLE_PATH="."
#name of your css file
USR_STYLE="styles.css"
#path to your image files location
USR_IMAGE_PATH="./images"
#name of your favicon file (should be in images folder)
FAVICON="favicon.ico"

header="<!DOCTYPE html>\n<html lang=\"en\">\n<head>\
\n\t<meta charset=\"utf-8\"/>\n\t<meta name=\"viewport\" content=\"\
width=device-width, initial-scale=1\"/>\n\t<title>$TITLE\
</title>\n\t<link rel=\"stylesheet\" href=\"$HL_PATH/styles/$HL_STYLE\">\
\n\t<link rel=\"stylesheet\" href=\"$USR_STYLE_PATH/$USR_STYLE\"/>\
\n\t<link rel=\"icon\" href=\"$USR_IMAGE_PATH/$FAVICON\"/>\
\n\t<script src=\"$HL_PATH/highlight.pack.js\"></script>\n\t\
<script>hljs.initHighlightingOnLoad();</script>\n</head>\n\n<body>\n\n"

tail="\n</body>\n</html>"

#add header to top, tail to bottom

touch ".temp_$filename"
cat "$filename" > ".temp_$filename"
printf "$header" > "$filename"
cat ".temp_$filename" >> "$filename"
printf "$tail" >> "$filename"
rm ".temp_$filename"
